### ISSUE TITLE
'logger' is not defined 

### ISSUE THREAD

**Issue by mudithauoc** [AIM-Harvard/pyradiomics#491]
I'm getting this error while trying to run featureextractor.py with US image and mask currently in jpg format. Can you please advice me on this

line 64, in __init__
    logger.info('No valid config parameter, using defaults: %s', self.settings)
NameError: name 'logger' is not defined

**Comment by JoostJM** [comment]
@mudithauoc, can you share the script you are using? I looked up the line in the source code, and logger should be defined by then. Only if the variable was deleted could it throw this error.

Moreover, what is the specific version of pyradiomics you are useing (cmdline: `pyradiomics --version`)

P.S. Since you are using jpg image and mask, did you implement code to select the correct color channel or is the JPG defined as grayscale?

**Comment by fedorov** [comment]
@mudithauoc were you able to resolve this issue?
