### ISSUE TITLE
Unable to install PyRadiomics via PIP (ADDITIONAL INFO NEEDED)

### ISSUE THREAD

**Issue by 2019lili** [AIM-Harvard/pyradiomics#518]
Why i can't download the pyradiomics sucessfully? Could you help me?
I have upgraded the PIP, and installed the Python 3.6, however,there is no success. Thanks a lot.

**Comment by pieper** [comment]
So people can help you better, please describe the steps you too, any error messages, your OS, etc.

**Comment by yszhong** [comment]
I've probably met the same problem, which is still unsolved. Let me show my steps and hope anyone can help. 
I use Python 3.8.3 and pip 20.1.1, run "pip install pyradiomics", when I met the description
`error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/`
when pip detected my PyWavelets is 1.1.1 and wants to downgrade it. I've tried installing the Visual C++ Building Tools, but it doesn't work. Sorry that I didn't record the error information befor I've uninstalled the toolkit. 
I know that using Anaconda to install pyradiomics is a safer way, and I've succeeded in that. But I need to build a .whl file to transfer the packages into other offline machines which doesn't have Anaconda in it, so pip freeze and install is a better way. And I don't know whether the file can work in Linux (e.g. CentOS 7) if I build a .whl in Windows 10.

**Comment by JoostJM** [comment]
Your error is caused by the fact that you don't have a c compiler configured on windows. This is needed to build the c extensions in PyRadiomics when building from source (wheels distributed on pypi come with precompiled extensions, but these are platform and python version specific). Currently python3.8 is not included in the regular distributions, so your pip actually gets the source code and tries to compile.

In some of the older closed issues in PyRadiomics you can find some pointers on how to set this up. However, as I mentioned, compiling is also platform specific, so compiled wheels on windows don't work for linux. Fortunately, linux comes with preconfigured c compilers, so it's likely the pip install will work on a linux machine.

**Comment by JoostJM** [comment]
Additionally, when configuring visual studio build tools (of the correct version!), ensure it is also added to the correct environment variables (smth like VS140COMNTOOLS)

**Comment by yszhong** [comment]
Thanks, I just pip installed PyRadiomics on  Linux, and I'll try to compile it on Windows later when I have time to.

**Comment by mohdsinad** [comment]
@yszhong I tried installing pyradiomics using Anaconda but gives the following error. Also, when I search for pyradiomics in the navigator, it doesn't give out any results. Please guide me on the same.
![cmd_S0nkQZkcMk](https://user-images.githubusercontent.com/61247376/97134064-0c007800-1772-11eb-9342-e97e15e6ccbb.png)
