### ISSUE TITLE
Feature extraction in Multiple ROI of one Tumors

### ISSUE THREAD

**Issue by Isaacshiri** [AIM-Harvard/pyradiomics#689]
In our recent studies we are using Pyradiomics as tools for feature extraction and we have a question on that. I would appreciate your response:
Some of the patients had more than one lesion in our study. In this study we provided multiple separated lesions segmented in a single mask all labeled one while background is zero.  Both images and segmentation masks were fed into the Pyradiomics  and a single set of features were extracted for each patient including patients with multiple lesions. But we still need to know the process, whether:

-All ROIs are considered as one, and calculated features? If this is the case how shape features would be interpreted and what would happen to the neighbors' respect to lesions in different locations for texture calculation?

-Features are calculated independently with each ROI, and then merged as one under some certain rules? if This is the case, where can I check the rules?

**Comment by JoostJM** [comment]
> All ROIs are considered as one, and calculated features? If this is the case how shape features would be interpreted and what would happen to the neighbors' respect to lesions in different locations for texture calculation?

Validity of shape features is questionable in this case. For example, Maximum Diameter now encodes the distance between lesions instead of a diameter. Texture features are more or less valid, in way, they are averaged over the different lesions. Texture features always and only use interconnected information (i.e. a neighbor is only a neighbor inside the same lesion, even if using a region growing principle such as in GLRLM and GLSZM). The calculated regions/neighbors are added in the same set of matrices though, hence the "averaging".

> Features are calculated independently with each ROI, and then merged as one under some certain rules? if This is the case, where can I check the rules?

No, though ususally I advise users to run a connected component image filter on the mask (assigning different labels to each spearate lesion, and the calculate features per lesion.
