### ISSUE TITLE
'RadiomicsFeatureExtractor' object has no attribute 'kwargs'[FEAT EXTRACTION]

### ISSUE THREAD

**Issue by Rezwanarosen** [AIM-Harvard/pyradiomics#719]
I wanted to see the extracted parameters by giving the command : print "Extraction parameters:\n\t", extractor.kwargs
But then the above error message shows up after running the code.

**Comment by JoostJM** [comment]
`kwargs` parameter in the feature extractor has long since been renamed to [`settings`](https://github.com/AIM-Harvard/pyradiomics/blob/master/radiomics/featureextractor.py#L50). This dictionary holds the settings applied during the extraction (not enabled features or image filters). This does not reflect the extracted parameters, these are returned by the `execute()` function.

**Comment by Rezwanarosen** [comment]
Thanks!
