### ISSUE TITLE
[BUG] Compactness1 feature implementation seems wrong?

### ISSUE THREAD

**Issue by skim2257** [AIM-Harvard/pyradiomics#746]
**Describe the bug**
The formula for Compactness 1 seems to be wrong? The original paper by Aerts et al, 2014 states compactness 1 to be V / (sqrt(pi) * A^(2/3)) as seen in the [Supplementary Figures](https://static-content.springer.com/esm/art%3A10.1038%2Fncomms5006/MediaObjects/41467_2014_BFncomms5006_MOESM716_ESM.pdf), page 14.

But the implemented code in [radiomics/shape.py](https://github.com/AIM-Harvard/pyradiomics/blob/2e0b76edefa60616c880ec0fbc54433ac03743db/radiomics/shape.py#L214) has the denominator: `self.surface_area ** (3.0 / 2.0)` instead of `2.0/3.0` as per the published formula. 

I can push a quick PR if this makes sense to the authors/maintainers.

**Comment by JoostJM** [comment]
@skim2257, the difference is intentional and due to an error in the original paper. Using the 3/2 exponential results in a non-dimensionless value (i.e. the range of values is dependent on the volume or surface area, instead of being bounded to 0 < compactness <= 1 / (6 * pi) ).

See commit dd7e831.
